### ISSUE TITLE
Based off?

### ISSUE THREAD

**Issue by d4rkd0s** [svdaddio/SecurityCenter#1]
@svdaddio is your repo/project based off of https://github.com/SteveMcGrath/pySecurityCenter ?

**Comment by svdaddio** [comment]
No, that guys is way better than the one I worked off of, in fact I'm going to use some of his code in my script. I was trying to figure out how to get the patch http verb to work, and that guy seems to have it working.

**Comment by svdaddio** [comment]
The code I worked from is located here: https://community.tenable.com/docs/DOC-1251

**Comment by d4rkd0s** [comment]
Ha @svdaddio do you want to just use that guys library, close this repo? Or get some ideas from that lib and deploy them here?

**Comment by svdaddio** [comment]
I will probably take some stuff from his and keep using my code because I
know how mine works. Also integrating his code will help me learn more lol.
